name: Rust CI

on:
  push:
    branches:
      - service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Build
      run: cargo build --release

    - name: Publish to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4
      with:
        branch: gh-pages
        folder: target/release
